name: Makefile CI

on:
  push:
    branches:
      - main
      - 'lbj-*'
  pull_request:
    branches:
      - main
      - 'lbj-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: make dev-install
      
    - name: Run tests
      run: make test
      
    - name: Run build
      run: make
